[debug]
address = "0.0.0.0"
port = 8000
workers = 32
keep_alive = 5
#secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[debug.databases.pocket_rocket]
url = "mysql://pr:pr@127.0.0.1:3306/pocket_rocket"
